### ISSUE TITLE
handleMkcol fails when the front proxy is Traefik with HTTP3 enabled

### ISSUE THREAD

**Issue by jochumdev** [opencloud-eu/reva#148]
Hi,

My front proxy runs HTTP3 seems that breaks

https://github.com/opencloud-eu/reva/blob/5a1172e6d178d77a6f14306d37b17078c6c962cf/internal/http/services/owncloud/ocdav/mkcol.go#L110

Can you remove this check?

Kind regards,
René

**Comment by jochumdev** [comment]
Maybe it's better and works when the client sends `Content-Length: 0` not sure.

**Comment by jochumdev** [comment]
@aduffeck ?

**Comment by jochumdev** [comment]
Yes, ofc.

Here is the traefik config I'm using in K3S: https://jochum.dev/en/20240502-traefikv3-on-kubernetes/

I'm using a Traefik IngressRoute on port 9200 to OpenCloud.

Simpler, setup Traefik with HTTP3 enabled using opencloud_full that should do the same job.

I believe `--entryPoints.name.https.advertisedport=443` is all you need to enable HTTP/3.

Want me to test this?

**Comment by jochumdev** [comment]
I was able to rebuild the same build without K3S.

## 1.) Save that file as `opencloud.yaml`

```yaml
name: opencloud01

include:
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/apps/opencloud-monolith/config/opencloud.yaml
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/apps/opencloud-monolith/config/traefik.yaml

repos:
  services:
    traefik:
      docker:
        # release notes: https://github.com/traefik/traefik/releases
        registry: docker.io
        image: library/traefik
        tag: v3.3.4
        command:
          - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
          - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
          - "--certificatesResolvers.http.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
          # define entrypoints
          - "--entryPoints.http.address=:80"
          - "--entryPoints.http.http.redirections.entryPoint.to=https"
          - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
          - "--entryPoints.https.address=:443"
          # change default timeouts for long-running requests
          # this is needed for webdav clients that do not support the TUS protocol
          - "--entryPoints.https.transport.respondingTimeouts.readTimeout=12h"
          - "--entryPoints.https.transport.respondingTimeouts.writeTimeout=12h"
          - "--entryPoints.https.transport.respondingTimeouts.idleTimeout=3m"
          # docker provider (get configuration from container labels)
          - "--providers.docker.endpoint=unix:///var/run/docker.sock"
          - "--providers.docker.exposedByDefault=false"
          # access log
          - "--accessLog=true"
          - "--accessLog.format=json"
          - "--accessLog.fields.headers.names.X-Request-Id=keep"
          # Enable HTTP/3
          - "--entrypoints.https.http3"
          - "--entryPoints.name.http3.advertisedport=443"

configs:
    collabora:
        admin:
            password: notSecure
            user: admin
    opencloud:
        domain:
            collabora: collabora.example.org
            companion: companion.example.org
            oc: cloud.example.org
            onlyoffice: onlyoffice.example.org
            wopiserver: wopiserver.example.org
        idp:
            adminPassword: notSecure
        smtp:
            authentication: plain
            host: mail.example.org
            insecure: "false"
            password: "notSecure"
            port: 587
            sender: OpenCloud notifications <cloud@example.org>
            username: cloud@example.org

    traefik:
        acme:
            email: support@example.org

octoctl:
  operator: docker

services:
  traefik:
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
```

### 2.) Configure for your needs

Replace example.org and notSecure

### 3.) Install octoctl

https://github.com/octocompose/octoctl 

```bash
curl -sL https://get.octocompose.dev | sh
```

### 4.) Start it

```bash
octoctl -c opencloud.yaml start
```
